# Homebrew CLI tools
brew "bat"
brew "distrobox"
brew "fd"
brew "fzf"
brew "gcc"
brew "lazygit"
brew "mise"
brew "neovim"
brew "rclone"
brew "ripgrep"
brew "starship"
brew "stow"

# Flatpak desktop applications
flatpak "com.brave.Browser", remote: "flathub"
flatpak "com.discordapp.Discord", remote: "flathub"
flatpak "com.fastmail.Fastmail", remote: "flathub"
flatpak "com.github.marhkb.Pods", remote: "flathub"
flatpak "com.github.tchx84.Flatseal", remote: "flathub"
flatpak "com.google.Chrome", remote: "flathub"
flatpak "com.spotify.Client", remote: "flathub"
flatpak "com.todoist.Todoist", remote: "flathub"
flatpak "com.usebruno.Bruno", remote: "flathub"
flatpak "dev.mufeed.Wordbook", remote: "flathub"
flatpak "dev.zed.Zed-Preview", remote: "flathub"
flatpak "io.github.flattool.Ignition", remote: "flathub"
flatpak "io.github.flattool.Warehouse", remote: "flathub"
flatpak "io.github.pieterdd.RcloneShuttle", remote: "flathub"
flatpak "io.github.ppvan.tarug", remote: "flathub"
flatpak "it.mijorus.gearlever", remote: "flathub"
flatpak "md.obsidian.Obsidian", remote: "flathub"
flatpak "net.nokyan.Resources", remote: "flathub"
flatpak "org.gnome.Solanum", remote: "flathub"
flatpak "org.gnome.gitlab.somas.Apostrophe", remote: "flathub"
flatpak "page.tesk.Refine", remote: "flathub"
