# ------------------------------------------------
# Main "developer" container.
# ------------------------------------------------
[dev]
image=quay.io/fedora/fedora-toolbox:42

# ------------------------------------------------
# Build containers isolate dependencies that are
# only required in order to build a given binary
# from source.
# ------------------------------------------------
[build-mise-erlang]
image=quay.io/fedora/fedora-toolbox:42
additional_packages="autoconf automake g++ ncurses-devel openssl-devel"
