- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    username: "{{ lookup('env', 'USER') }}"
    ssh_key_passphrase: "{{ lookup('env', 'SSH_KEY_PASSPHRASE') }}"
  roles:
    - role: packages
      become: true

    - role: dotfiles
    - role: flatpak
    - role: gnome
    - role: appimages
    - role: ssh

