- name: Add Brave browser repository
  get_url:
    url: https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    dest: /etc/yum.repos.d/brave-browser.repo
    mode: '0644'

- name: Install Brave browser
  dnf:
    name: brave-browser
    state: present


