- name: Install CLI tools
  dnf:
    name:
      - bat
      - curl
      - dnf-plugins-core
      - fd-find
      - fzf
      - git
      - gpg
      - inotify-tools
      - jq
      - neovim
      - stow
      - tree
      - wget
      - wireguard-tools
      - zsh
    state: present

- name: Ensure /bin/zsh is listed in /etc/shells
  lineinfile:
    path: /etc/shells
    line: /bin/zsh
    state: present

- name: Ensure ZSH is the default shell
  user:
    name: "{{ username }}"
    shell: /bin/zsh

