- name: Download ExpressVPN RPM
  get_url:
    url: https://www.expressvpn.com/download/linux
    dest: /tmp/expressvpn.rpm

- name: Install ExpressVPN
  dnf:
    name: /tmp/expressvpn.rpm
    state: present

