- name: Enable Ghostty COPR
  command: dnf copr enable -y pgdev/ghostty
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:pgdev:ghostty.repo

- name: Install Ghostty
  dnf:
    name: ghostty
    state: present

