- name: Import 1Password GPG key
  rpm_key:
    key: https://downloads.1password.com/linux/keys/1password.asc
    state: present

- name: Add 1Password repository
  copy:
    dest: /etc/yum.repos.d/1password.repo
    content: |
      [1password]
      name=1Password Stable Channel
      baseurl=https://downloads.1password.com/linux/rpm/stable/$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://downloads.1password.com/linux/keys/1password.asc
      metadata_expire=1h

- name: Install 1Password
  dnf:
    name: 1password
    state: present

