- name: Enable WezTerm COPR
  command: dnf copr enable -y wezfurlong/wezterm-nightly
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:wezfurlong:wezterm-nightly.repo

- name: Install WezTerm
  dnf:
    name: wezterm
    state: present

