- name: Ensure ~/code directory exists
  file:
    path: "{{ home_dir }}/code"
    state: directory
    mode: '0755'

- name: Clone dotfiles repository
  git:
    repo: "https://github.com/monooso/dotfiles"
    dest: "{{ home_dir }}/code/dotfiles"
    version: main
    update: yes

- name: Install GNU Stow
  become: true
  dnf:
    name: stow
    state: present

- name: Symlink dotfiles using Stow
  command: stow -t {{ home_dir }} .
  args:
    chdir: "{{ home_dir }}/code/dotfiles"

