- name: Ensure SSH keys directory exists
  file:
    path: "{{ home_dir }}/.ssh/keys.d"
    state: directory
    mode: '0700'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Generate SSH key if it doesn't exist
  command: >
    ssh-keygen -t ed25519 -C "default key" -f "{{ home_dir }}/.ssh/keys.d/default" -N "{{ ssh_key_passphrase }}"
  args:
    creates: "{{ home_dir }}/.ssh/keys.d/default"

