- name: Enable GNOME dark mode
  become: false
  command: gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
  args:
    executable: /bin/bash
  environment:
    DISPLAY: :0
    XDG_CURRENT_DESKTOP: GNOME
  changed_when: false

