- name: Set user keyboard layout to English (Colemak-DH)
  tags: keyboard
  shell: |
    gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us+colemak_dh')]"
  environment:
    DISPLAY: :0
    XDG_CURRENT_DESKTOP: GNOME
  changed_when: false

- name: Remap CapsLock to Ctrl
  tags: keyboard
  shell: |
    gsettings set org.gnome.desktop.input-sources xkb-options "['caps:ctrl_modifier']"
  environment:
    DISPLAY: :0
    XDG_CURRENT_DESKTOP: GNOME
  changed_when: false

