- name: Install Pop Shell extension
  become: true
  dnf:
    name: gnome-shell-extension-pop-shell
    state: present

- name: Enable Pop Shell extension
  shell: |
    gnome-extensions enable pop-shell@system76.com
  args:
    executable: /bin/bash
  environment:
    DISPLAY: :0
    XDG_CURRENT_DESKTOP: GNOME
  changed_when: false

