- name: Ensure Pictures directory exists
  file:
    path: "{{ home_dir }}/Pictures/Wallpapers"
    state: directory
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy wallpaper to ~/Pictures/Wallpapers directory
  copy:
    src: assets/wallpapers/cut-paper-swirl.webp
    dest: "{{ home_dir }}/Pictures/Wallpapers/cut-paper-swirl.webp"
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Set GNOME wallpaper
  shell: |
    gsettings set org.gnome.desktop.background picture-uri 'file:///{{ home_dir }}/Pictures/Wallpapers/cut-paper-swirl.webp'
    gsettings set org.gnome.desktop.background picture-uri-dark 'file:///{{ home_dir }}/Pictures/Wallpapers/cut-paper-swirl.webp'
  args:
    executable: /bin/bash
  environment:
    DISPLAY: :0
    XDG_CURRENT_DESKTOP: GNOME
  changed_when: false

