- name: Ensure Pictures directory exists
  file:
    path: "{{ home_dir }}/Pictures"
    state: directory
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Download selected wallpaper
  get_url:
    url: https://images.pexels.com/photos/1293120/pexels-photo-1293120.jpeg
    dest: "{{ home_dir }}/Pictures/wallpaper.jpg"
    mode: '0644'
    force: yes

- name: Set GNOME wallpaper
  shell: |
    gsettings set org.gnome.desktop.background picture-uri 'file://{{ home_dir }}/Pictures/wallpaper.jpg'
  args:
    executable: /bin/bash
  environment:
    DISPLAY: :0
    XDG_CURRENT_DESKTOP: GNOME
  changed_when: false

